---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omux-io
spec:
  dnsNames:
    - omux.io
    - "*.omux.io"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: omux-io-tls
  usages:
    - digital signature
