---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./postfinance.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
